export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "https://img.freepik.com/free-photo/couple-family-traveling-together_1150-7772.jpg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "./assets/1.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "./assets/1.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "./assets/1.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "./assets/1.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "./assets/1.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "./assets/1.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "./assets/1.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "./assets/1.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https:img.freepik.com/free-photo/attractive-blonde-woman-sunglasses-man-white-tee-smiles-takes-selfie-near-airport_197531-23097.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://img.freepik.com/free-photo/couple-family-traveling-together_1150-7772.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo:"https://www.shutterstock.com/shutterstock/photos/2259995365/display_1500/stock-photo-travel-airport-and-excited-woman-with-passport-travel-ticket-and-documents-for-immigration-2259995365.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://images.huffingtonpost.com/2016-01-22-1453422849-2843535-Traveling-thumb.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://heymondo.com/blog/wp-content/uploads/2021/03/shutterstock_757552030_compressed.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dHJhdmVsJTIwcGVvcGxlfGVufDB8fDB8fHww",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://www.shutterstock.com/image-photo/beautiful-girl-points-hawa-mahal-260nw-754382752.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  // {
  //   id: 8,
  //   photo: "./assets/1.jpeg",
  //   date: "3 days ago",
  //   userId: 8,
  //   like: 15,
  //   comment: 1,
  // },
  // {
  //   id: 9,
  //   desc: "Change the world by being yourself.",
  //   photo: "./assets/1.jpeg",
  //   date: "5 days ago",
  //   userId: 9,
  //   like: 11,
  //   comment: 2,
  // },
  // {
  //   id: 10,
  //   photo: "./assets/1.jpeg",
  //   date: "1 week ago",
  //   userId: 10,
  //   like: 104,
  //   comment: 12,
  // },
];